### ISSUE TITLE
Superclass mismatch for class HashWithIndifferentAccess when not including all gems

### ISSUE THREAD

**Issue by d3vkit** [colinyoung/cancan_strong_parameters#3]
If I add only the gem 'cancan_strong_parameters' to my gemfile, I get an error when loading `rails c` or `rails g cancan:ability`; if I add cancan, strong_parameters, and cancan_strong_parameters, I don't have this issue. Using Rails 3.2.8 and ruby-1.9.3-p286, on Ubuntu 12.10. I saw the one other very vague issue here, and this might be what the user was talking about, but I couldn't be sure so I have created this new issue. Thanks!

``` ruby
d3vkit@red-5:/var/www/myapp$ rails c
/home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/hash_with_indifferent_access.rb:8:in `<module:ActiveSupport>': superclass mismatch for class HashWithIndifferentAccess (TypeError)
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/hash_with_indifferent_access.rb:7:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/core_ext/hash/indifferent_access.rb:1:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/actionpack-3.2.8/lib/action_dispatch/http/request.rb:5:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/actionpack-3.2.8/lib/action_controller/metal/rack_delegation.rb:1:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/actionpack-3.2.8/lib/action_controller/metal/redirecting.rb:14:in `<module:Redirecting>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/actionpack-3.2.8/lib/action_controller/metal/redirecting.rb:10:in `<module:ActionController>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/actionpack-3.2.8/lib/action_controller/metal/redirecting.rb:1:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/actionpack-3.2.8/lib/action_controller/base.rb:190:in `<class:Base>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/actionpack-3.2.8/lib/action_controller/base.rb:171:in `<module:ActionController>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/actionpack-3.2.8/lib/action_controller/base.rb:3:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/cancan_strong_parameters-0.2/lib/cancan_strong_parameters/rails/controller/base.rb:1:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/cancan_strong_parameters-0.2/lib/cancan_strong_parameters.rb:4:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/cancan_strong_parameters-0.2/lib/cancan_strong_parameters.rb:4:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:68:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:66:in `each'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:66:in `block in require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:55:in `each'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler/runtime.rb:55:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@global/gems/bundler-1.2.1/lib/bundler.rb:128:in `require'
  from /var/www/myapp/config/application.rb:7:in `<top (required)>'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/railties-3.2.8/lib/rails/commands.rb:39:in `require'
  from /home/d3vkit/.rvm/gems/ruby-1.9.3-p286@myapp/gems/railties-3.2.8/lib/rails/commands.rb:39:in `<top (required)>'
  from script/rails:6:in `require'
  from script/rails:6:in `<main>'
```

Here is my gemfile if that will help any:

``` ruby
source 'https://rubygems.org'
gem 'rails', '3.2.8'
gem 'pg'
gem 'cancan'
gem 'strong_parameters'
gem 'cancan_strong_parameters'
gem 'coffee-rails', '~> 3.2.1'
gem 'simple_form'
gem "slim-rails"

group :assets do
  gem 'sass-rails',   '~> 3.2.3'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', platforms: :ruby
  gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
  gem 'twitter-bootstrap-rails', git: 'git://github.com/seyhunak/twitter-bootstrap-rails.git'

  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'rvm-capistrano'
  gem 'quiet_assets'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'

gem 'passenger'

# Deploy with Capistrano
gem 'capistrano'
```

**Comment by colinyoung** [comment]
Thanks, this is a great point. Just needed to `require 'activesupport/hash_with_indifferent_access'`.
